server:
  port: 8022
spring:
  profiles:
    active: local
  application:
    name: notification-service

---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    template:
      default-topic: tx-event-v2
    consumer:
      bootstrap-servers: localhost:9092,localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: trans-event-group
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
    listener:
      ack-mode: RECORD
