server:
  port: 8021
spring:
  profiles:
    active: local
  application:
    name: account-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/locdb
    username: root
    password: Tesla@1234
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    topic: trans-event
    template:
      default-topic: trans-event
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer